apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 2 # Update the replica count to 3
  template:
    spec:
      containers:
        - name: java-example
          image: public.ecr.aws/q0y1s1a8/java-example
          # resources:
          #   limits:
          #     cpu: "200" # Lower CPU limit to 200m (0.2 CPU cores)
          #     memory: "256Mi" # Lower memory limit to 256 MiB
          #   requests:
          #     cpu: "100" # Lower CPU request to 100m (0.1 CPU cores)
          #     memory: "128Mi"
