apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: java-example
          image: public.ecr.aws/q0y1s1a8/java-example
          ports:
            - containerPort: 80
